import {
  Atom,
  Bot,
  Boxes,
  Braces,
  Cable,
  Coffee,
  Container,
  Database,
  FlaskConical,
  GitBranch,
  Globe,
  IdCard,
  KeyRound,
  Layers,
  Network,
  Radar,
  Rocket,
  ScanText,
  Server,
  Share2,
  Sparkles,
  Terminal,
  TestTubes,
  Wind,
  Workflow,
  Zap,
} from "lucide-react";
import type { InventoryCategory, InventoryItem } from "./types";

/**
 * ── INVENTORY ─────────────────────────────────────────────────
 * The tech stack as game items. rarity drives the tile glow:
 * legendary (gold) > epic (arcane purple) > rare (system blue) > common.
 * `category` must match a category id below. mastery is 0–100.
 */
export const inventoryCategories: InventoryCategory[] = [
  { id: "artifacts", name: "ARTIFACTS", icon: KeyRound },
  { id: "ai", name: "AI ARSENAL", icon: Bot },
  { id: "languages", name: "LANGUAGES", icon: Terminal },
  { id: "web", name: "WEB GEAR", icon: Layers },
  { id: "data", name: "DATA VAULTS", icon: Database },
  { id: "ops", name: "OPS RELICS", icon: Container },
];

export const inventoryItems: InventoryItem[] = [
  // ── ARTIFACTS ───────────────────────────────────────────────
  {
    id: "hunter-license",
    name: "Hunter's License",
    icon: IdCard,
    category: "artifacts",
    rarity: "legendary",
    mastery: 100,
    lore: "Official proof of the Player's rank, raids and titles. Inspect it to open the DOSSIER — the complete record, ready to extract.",
    tags: ["cv", "resume", "official-record"],
    unlocks: "cv",
  },

  // ── AI ARSENAL ──────────────────────────────────────────────
  {
    id: "langgraph",
    name: "LangChain / LangGraph",
    icon: Workflow,
    category: "ai",
    rarity: "legendary",
    mastery: 93,
    lore: "Primary weapon. Forges LLM-driven workflows and stateful agent graphs — every serious raid starts here.",
    tags: ["agents", "workflows", "python"],
  },
  {
    id: "mcp",
    name: "MCP Protocol",
    icon: Cable,
    category: "ai",
    rarity: "legendary",
    mastery: 90,
    lore: "Artifact of connection. Grounds agents in enterprise systems and rich contextual data across any boundary.",
    tags: ["context", "integration"],
  },
  {
    id: "copilotkit",
    name: "CopilotKit / AG-UI",
    icon: Sparkles,
    category: "ai",
    rarity: "epic",
    mastery: 89,
    lore: "Bridge between realms. Lets humans and agents share one interface — the same magic that will soon awaken this System.",
    tags: ["human-ai", "frontend"],
  },
  {
    id: "langsmith",
    name: "LangSmith",
    icon: Radar,
    category: "ai",
    rarity: "epic",
    mastery: 88,
    lore: "All-seeing eye. Traces every agent step, exposing the invisible paths a thought takes through the graph.",
    tags: ["observability", "tracing"],
  },
  {
    id: "rag",
    name: "RAG Systems",
    icon: ScanText,
    category: "ai",
    rarity: "epic",
    mastery: 90,
    lore: "Tome of recall. Retrieval-grounded generation over knowledge graphs and raw archives.",
    tags: ["retrieval", "knowledge-graph"],
  },
  {
    id: "keras",
    name: "Keras / Deep Learning",
    icon: FlaskConical,
    category: "ai",
    rarity: "rare",
    mastery: 78,
    lore: "Alchemist's kit. BiLSTM taggers and CNN vision pipelines were brewed with this in earlier arcs.",
    tags: ["ml", "nlp", "cnn"],
  },

  // ── LANGUAGES ───────────────────────────────────────────────
  {
    id: "python",
    name: "Python",
    icon: Braces,
    category: "languages",
    rarity: "legendary",
    mastery: 92,
    lore: "Ancestral blade of the AI arts. Fluent, fast to draw, sharp at any scale.",
    tags: ["backend", "ai"],
  },
  {
    id: "typescript",
    name: "TypeScript",
    icon: Braces,
    category: "languages",
    rarity: "legendary",
    mastery: 90,
    lore: "Enchanted armor for JavaScript. Types are wards — breaches are caught before the dungeon door opens.",
    tags: ["frontend", "backend"],
  },
  {
    id: "javascript",
    name: "JavaScript",
    icon: Zap,
    category: "languages",
    rarity: "epic",
    mastery: 88,
    lore: "The common tongue of the web realm. Spoken everywhere, mastered by few.",
    tags: ["web"],
  },
  {
    id: "java",
    name: "Java",
    icon: Coffee,
    category: "languages",
    rarity: "rare",
    mastery: 80,
    lore: "Heavy greatsword. Slower to swing, but Spring Boot raids were cleared with it.",
    tags: ["backend", "spring"],
  },

  // ── WEB GEAR ────────────────────────────────────────────────
  {
    id: "nextjs",
    name: "Next.js / React",
    icon: Atom,
    category: "web",
    rarity: "legendary",
    mastery: 90,
    lore: "Twin daggers of the frontend. Server components, streaming, static sorcery — this very System is forged with them.",
    tags: ["react", "ssr"],
  },
  {
    id: "fastapi",
    name: "FastAPI",
    icon: Rocket,
    category: "web",
    rarity: "epic",
    mastery: 87,
    lore: "Swift courier of the backend. Async endpoints that serve agent minds at speed.",
    tags: ["python", "api"],
  },
  {
    id: "tailwind",
    name: "Tailwind CSS / shadcn/ui",
    icon: Wind,
    category: "web",
    rarity: "epic",
    mastery: 88,
    lore: "Tailor's charm. Interfaces cut precisely to measure, no stylesheet left behind.",
    tags: ["ui", "design-system"],
  },
  {
    id: "zustand",
    name: "Zustand / Redux Toolkit",
    icon: Boxes,
    category: "web",
    rarity: "rare",
    mastery: 84,
    lore: "Keeper of state. This OS window manager answers to it right now.",
    tags: ["state"],
  },
  {
    id: "auth",
    name: "Auth.js / KindeAuth",
    icon: KeyRound,
    category: "web",
    rarity: "rare",
    mastery: 82,
    lore: "Gatekeeper's seal. Decides who may pass and who is turned away.",
    tags: ["auth", "security"],
  },
  {
    id: "cypress",
    name: "Cypress / next-intl",
    icon: TestTubes,
    category: "web",
    rarity: "common",
    mastery: 80,
    lore: "Field kit. End-to-end trials and tongues for every region.",
    tags: ["testing", "i18n"],
  },

  // ── DATA VAULTS ─────────────────────────────────────────────
  {
    id: "postgres",
    name: "PostgreSQL",
    icon: Database,
    category: "data",
    rarity: "epic",
    mastery: 86,
    lore: "The deep vault. Relational bedrock that has never dropped a single coin.",
    tags: ["sql"],
  },
  {
    id: "neo4j",
    name: "Neo4j",
    icon: Share2,
    category: "data",
    rarity: "epic",
    mastery: 84,
    lore: "Web of fate. Knowledge graphs that let agents see how everything connects.",
    tags: ["graph", "knowledge-graph"],
  },
  {
    id: "redis",
    name: "Redis",
    icon: Zap,
    category: "data",
    rarity: "rare",
    mastery: 80,
    lore: "Lightning satchel. Whatever it holds, it hands back before you finish asking.",
    tags: ["cache"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    icon: Boxes,
    category: "data",
    rarity: "rare",
    mastery: 78,
    lore: "Shapeshifter's chest. Documents of any form find a place inside.",
    tags: ["nosql"],
  },
  {
    id: "mysql",
    name: "MySQL",
    icon: Database,
    category: "data",
    rarity: "common",
    mastery: 78,
    lore: "Trusty starter vault. Old, reliable, still in rotation.",
    tags: ["sql"],
  },

  // ── OPS RELICS ──────────────────────────────────────────────
  {
    id: "docker",
    name: "Docker / Compose",
    icon: Container,
    category: "ops",
    rarity: "epic",
    mastery: 85,
    lore: "Dimensional crates. Any beast, sealed and shipped to any realm unchanged.",
    tags: ["containers"],
  },
  {
    id: "cicd",
    name: "GitHub Actions / CI-CD",
    icon: Workflow,
    category: "ops",
    rarity: "epic",
    mastery: 84,
    lore: "Clockwork familiar. Builds, tests and deploys while the Player sleeps.",
    tags: ["automation"],
  },
  {
    id: "git",
    name: "Git / GitHub / GitLab",
    icon: GitBranch,
    category: "ops",
    rarity: "epic",
    mastery: 88,
    lore: "Chronicle stone. Every timeline preserved; any mistake, rewound.",
    tags: ["vcs"],
  },
  {
    id: "observability",
    name: "Prometheus / Grafana / OTel",
    icon: Radar,
    category: "ops",
    rarity: "rare",
    mastery: 78,
    lore: "Scrying array. Metrics, traces and dashboards — nothing moves unseen.",
    tags: ["monitoring"],
  },
  {
    id: "linux",
    name: "Linux / Unix",
    icon: Server,
    category: "ops",
    rarity: "epic",
    mastery: 86,
    lore: "Homeland terrain. The Player fights best on native ground.",
    tags: ["os", "shell"],
  },
  {
    id: "web-standards",
    name: "HTTP / REST / WebSockets",
    icon: Globe,
    category: "ops",
    rarity: "rare",
    mastery: 85,
    lore: "Trade routes of the realm. Every message travels one of these roads.",
    tags: ["protocols"],
  },
  {
    id: "architecture",
    name: "System Design / MAS Patterns",
    icon: Network,
    category: "ops",
    rarity: "legendary",
    mastery: 91,
    lore: "Blueprint of the citadel. Modular, scalable agent architectures — the meta-skill behind every other item here.",
    tags: ["architecture", "multi-agent"],
  },
];
