import {
  Atom,
  Boxes,
  Bot,
  Braces,
  Cable,
  Coffee,
  Container,
  Database,
  Ear,
  FlaskConical,
  Flag,
  GitBranch,
  Globe,
  Headphones,
  Landmark,
  Layers,
  Lightbulb,
  MessagesSquare,
  Network,
  Radar,
  Rocket,
  ScanText,
  Server,
  Share2,
  Shuffle,
  Sparkles,
  Swords,
  Telescope,
  Terminal,
  TestTubes,
  TowerControl,
  Users,
  Wind,
  Workflow,
  Zap,
} from "lucide-react";
import type { SkillCategoryDef, SkillDetail, SkillSetDef } from "./types";

/**
 * ── SKILL TREE ────────────────────────────────────────────────
 * Two sets: `job` (the Player's craft) and `secondary` (everything
 * the job isn't — tongues, soft skills, pursuits). Mastery is
 * 0–100 and maps to grades in the UI: ≥90 S · ≥85 A · ≥78 B · else C.
 * rarity drives the glow: legendary > epic > rare > common.
 * Clicking any skill opens its lore in the INFO window.
 */
export const skillSets: SkillSetDef[] = [
  {
    id: "job",
    name: "JOB SKILLS",
    blurb: "class: agentic systems developer — active combat kit",
  },
  {
    id: "secondary",
    name: "SECONDARY SKILLS",
    blurb: "passives acquired outside the job — always equipped",
  },
];

export const skillCategories: SkillCategoryDef[] = [
  // ── job ──
  { id: "ai-arch", name: "AI Architectures & Principles", icon: Network, set: "job", tone: "arcane" },
  { id: "agent-stack", name: "AI Agent Stack", icon: Bot, set: "job", tone: "arcane" },
  { id: "languages", name: "Programming Languages", icon: Terminal, set: "job", tone: "system" },
  { id: "web", name: "Web Development", icon: Layers, set: "job", tone: "system" },
  { id: "data", name: "Databases", icon: Database, set: "job", tone: "gold" },
  { id: "ops", name: "DevOps & Observability", icon: Container, set: "job", tone: "ember" },
  // ── secondary ──
  { id: "tongues", name: "Tongues", icon: MessagesSquare, set: "secondary", tone: "system" },
  { id: "soft", name: "Soft Skills", icon: Users, set: "secondary", tone: "gold" },
  { id: "pursuits", name: "Pursuits", icon: Swords, set: "secondary", tone: "arcane" },
];

export const skills: SkillDetail[] = [
  // ── AI ARCHITECTURES & PRINCIPLES ───────────────────────────
  {
    id: "ai-agents",
    name: "AI Agents",
    icon: Bot,
    category: "ai-arch",
    rarity: "legendary",
    mastery: 95,
    lore: "The signature art. Autonomous entities given goals, tools and memory — raised to act in the world, not just answer it.",
    tags: ["autonomy", "tool-use"],
  },
  {
    id: "multi-agent-systems",
    name: "Multi-Agent Systems",
    icon: Network,
    category: "ai-arch",
    rarity: "legendary",
    mastery: 92,
    lore: "Blueprint of the citadel. Specialized agents coordinated into modular, scalable architectures — the meta-skill behind every raid.",
    tags: ["architecture", "orchestration"],
  },
  {
    id: "context-engineering",
    name: "Context Engineering",
    icon: ScanText,
    category: "ai-arch",
    rarity: "legendary",
    mastery: 94,
    lore: "Mana shaping. Deciding what an agent perceives — the difference between a sharp mind and a drowned one.",
    tags: ["context", "reliability"],
  },
  {
    id: "prompt-engineering",
    name: "Prompt Engineering",
    icon: Sparkles,
    category: "ai-arch",
    rarity: "legendary",
    mastery: 93,
    lore: "Incantation craft. Words arranged so reasoning holds under pressure and output lands exactly where aimed.",
    tags: ["reasoning", "quality"],
  },
  {
    id: "rag-systems",
    name: "RAG Systems",
    icon: ScanText,
    category: "ai-arch",
    rarity: "legendary",
    mastery: 90,
    lore: "Tome of recall. Retrieval-grounded generation over knowledge graphs and raw archives.",
    tags: ["retrieval", "knowledge-graph"],
  },
  {
    id: "ai-workflows",
    name: "AI-driven Workflows",
    icon: Workflow,
    category: "ai-arch",
    rarity: "legendary",
    mastery: 91,
    lore: "Clockwork rituals. LLM-driven pipelines that carry work from raw input to finished act without a hand on the wheel.",
    tags: ["automation", "llm"],
  },

  // ── AI AGENT STACK ──────────────────────────────────────────
  {
    id: "langgraph",
    name: "LangChain / LangGraph",
    icon: Workflow,
    category: "agent-stack",
    rarity: "legendary",
    mastery: 93,
    lore: "Primary weapon. Forges LLM-driven workflows and stateful agent graphs — every serious raid starts here.",
    tags: ["agents", "workflows", "python"],
  },
  {
    id: "langsmith",
    name: "LangSmith",
    icon: Radar,
    category: "agent-stack",
    rarity: "epic",
    mastery: 88,
    lore: "All-seeing eye. Traces every agent step, exposing the invisible paths a thought takes through the graph.",
    tags: ["observability", "tracing"],
  },
  {
    id: "mcp",
    name: "MCP Protocol",
    icon: Cable,
    category: "agent-stack",
    rarity: "legendary",
    mastery: 90,
    lore: "Artifact of connection. Grounds agents in enterprise systems and rich contextual data across any boundary.",
    tags: ["context", "integration"],
  },
  {
    id: "copilotkit",
    name: "CopilotKit / AG-UI",
    icon: Sparkles,
    category: "agent-stack",
    rarity: "epic",
    mastery: 89,
    lore: "Bridge between realms. Lets humans and agents share one interface — the same magic that will soon awaken this System.",
    tags: ["human-ai", "frontend"],
  },
  {
    id: "keras",
    name: "Keras / Deep Learning",
    icon: FlaskConical,
    category: "agent-stack",
    rarity: "rare",
    mastery: 78,
    lore: "Alchemist's kit. BiLSTM taggers and CNN vision pipelines were brewed with this in earlier arcs.",
    tags: ["ml", "nlp", "cnn"],
  },

  // ── PROGRAMMING LANGUAGES ───────────────────────────────────
  {
    id: "python",
    name: "Python",
    icon: Braces,
    category: "languages",
    rarity: "legendary",
    mastery: 92,
    lore: "Ancestral blade of the AI arts. Fluent, fast to draw, sharp at any scale.",
    tags: ["backend", "ai"],
  },
  {
    id: "typescript",
    name: "TypeScript",
    icon: Braces,
    category: "languages",
    rarity: "legendary",
    mastery: 90,
    lore: "Enchanted armor for JavaScript. Types are wards — breaches are caught before the dungeon door opens.",
    tags: ["frontend", "backend"],
  },
  {
    id: "javascript",
    name: "JavaScript",
    icon: Zap,
    category: "languages",
    rarity: "epic",
    mastery: 88,
    lore: "The common tongue of the web realm. Spoken everywhere, mastered by few.",
    tags: ["web"],
  },
  {
    id: "java",
    name: "Java",
    icon: Coffee,
    category: "languages",
    rarity: "rare",
    mastery: 80,
    lore: "Heavy greatsword. Slower to swing, but Spring Boot raids were cleared with it.",
    tags: ["backend", "spring"],
  },

  // ── WEB DEVELOPMENT ─────────────────────────────────────────
  {
    id: "nextjs",
    name: "Next.js / React",
    icon: Atom,
    category: "web",
    rarity: "legendary",
    mastery: 90,
    lore: "Twin daggers of the frontend. Server components, streaming, static sorcery — this very System is forged with them.",
    tags: ["react", "ssr"],
  },
  {
    id: "fastapi",
    name: "FastAPI",
    icon: Rocket,
    category: "web",
    rarity: "epic",
    mastery: 87,
    lore: "Swift courier of the backend. Async endpoints that serve agent minds at speed.",
    tags: ["python", "api"],
  },
  {
    id: "tailwind",
    name: "Tailwind CSS / shadcn/ui",
    icon: Wind,
    category: "web",
    rarity: "epic",
    mastery: 88,
    lore: "Tailor's charm. Interfaces cut precisely to measure, no stylesheet left behind.",
    tags: ["ui", "design-system"],
  },
  {
    id: "state-management",
    name: "Zustand / Redux Toolkit",
    icon: Boxes,
    category: "web",
    rarity: "rare",
    mastery: 84,
    lore: "Keeper of state. This OS window manager answers to it right now.",
    tags: ["state"],
  },
  {
    id: "zod-drizzle",
    name: "Zod / Drizzle ORM",
    icon: Layers,
    category: "web",
    rarity: "rare",
    mastery: 83,
    lore: "Contract seals. Schemas that promise a shape and keep it, from form to table.",
    tags: ["validation", "orm"],
  },
  {
    id: "auth",
    name: "Auth.js / KindeAuth",
    icon: TowerControl,
    category: "web",
    rarity: "rare",
    mastery: 82,
    lore: "Gatekeeper's seal. Decides who may pass and who is turned away.",
    tags: ["auth", "security"],
  },
  {
    id: "cypress-intl",
    name: "Cypress / next-intl",
    icon: TestTubes,
    category: "web",
    rarity: "common",
    mastery: 80,
    lore: "Field kit. End-to-end trials and tongues for every region.",
    tags: ["testing", "i18n"],
  },

  // ── DATABASES ───────────────────────────────────────────────
  {
    id: "postgres",
    name: "PostgreSQL",
    icon: Database,
    category: "data",
    rarity: "epic",
    mastery: 86,
    lore: "The deep vault. Relational bedrock that has never dropped a single coin.",
    tags: ["sql"],
  },
  {
    id: "neo4j",
    name: "Neo4j",
    icon: Share2,
    category: "data",
    rarity: "epic",
    mastery: 84,
    lore: "Web of fate. Knowledge graphs that let agents see how everything connects.",
    tags: ["graph", "knowledge-graph"],
  },
  {
    id: "redis",
    name: "Redis",
    icon: Zap,
    category: "data",
    rarity: "rare",
    mastery: 80,
    lore: "Lightning satchel. Whatever it holds, it hands back before you finish asking.",
    tags: ["cache"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    icon: Boxes,
    category: "data",
    rarity: "rare",
    mastery: 78,
    lore: "Shapeshifter's chest. Documents of any form find a place inside.",
    tags: ["nosql"],
  },
  {
    id: "mysql",
    name: "MySQL",
    icon: Database,
    category: "data",
    rarity: "common",
    mastery: 78,
    lore: "Trusty starter vault. Old, reliable, still in rotation.",
    tags: ["sql"],
  },

  // ── DEVOPS & OBSERVABILITY ──────────────────────────────────
  {
    id: "docker",
    name: "Docker / Compose",
    icon: Container,
    category: "ops",
    rarity: "epic",
    mastery: 85,
    lore: "Dimensional crates. Any beast, sealed and shipped to any realm unchanged.",
    tags: ["containers"],
  },
  {
    id: "cicd",
    name: "GitHub Actions / CI-CD",
    icon: Workflow,
    category: "ops",
    rarity: "epic",
    mastery: 84,
    lore: "Clockwork familiar. Builds, tests and deploys while the Player sleeps.",
    tags: ["automation"],
  },
  {
    id: "git",
    name: "Git / GitHub / GitLab",
    icon: GitBranch,
    category: "ops",
    rarity: "epic",
    mastery: 88,
    lore: "Chronicle stone. Every timeline preserved; any mistake, rewound.",
    tags: ["vcs"],
  },
  {
    id: "observability",
    name: "Prometheus / Grafana / OTel",
    icon: Radar,
    category: "ops",
    rarity: "rare",
    mastery: 78,
    lore: "Scrying array. Metrics, traces and dashboards — nothing moves unseen.",
    tags: ["monitoring"],
  },
  {
    id: "linux",
    name: "Linux / Unix",
    icon: Server,
    category: "ops",
    rarity: "epic",
    mastery: 86,
    lore: "Homeland terrain. The Player fights best on native ground.",
    tags: ["os", "shell"],
  },
  {
    id: "web-standards",
    name: "HTTP / REST / WebSockets",
    icon: Globe,
    category: "ops",
    rarity: "rare",
    mastery: 85,
    lore: "Trade routes of the realm. Every message travels one of these roads.",
    tags: ["protocols"],
  },

  // ── TONGUES ─────────────────────────────────────────────────
  {
    id: "arabic",
    name: "Arabic",
    icon: MessagesSquare,
    category: "tongues",
    rarity: "legendary",
    mastery: 100,
    lore: "Mother tongue. Native fluency — the language the Player thinks in.",
    tags: ["native"],
  },
  {
    id: "english",
    name: "English",
    icon: MessagesSquare,
    category: "tongues",
    rarity: "epic",
    mastery: 88,
    lore: "Trade tongue of the tech realm. Proficient — specs, papers and raids are run in it daily.",
    tags: ["proficient"],
  },
  {
    id: "french",
    name: "French",
    icon: MessagesSquare,
    category: "tongues",
    rarity: "rare",
    mastery: 75,
    lore: "Technical dialect. Reads documentation and holds a meeting without dropping the thread.",
    tags: ["technical"],
  },

  // ── SOFT SKILLS ─────────────────────────────────────────────
  {
    id: "future-vision",
    name: "Future-Focused Vision",
    icon: Telescope,
    category: "soft",
    rarity: "legendary",
    mastery: 90,
    lore: "Foresight passive. Reads where software is heading — LLMs as operating systems, language as the interface — and builds there early.",
    tags: ["strategy"],
  },
  {
    id: "analytical-thinking",
    name: "Analytical Thinking",
    icon: Lightbulb,
    category: "soft",
    rarity: "legendary",
    mastery: 92,
    lore: "Debuff immunity to hand-waving. Problems decomposed until each piece is small enough to defeat.",
    tags: ["reasoning"],
  },
  {
    id: "team-collaboration",
    name: "Team Collaboration",
    icon: Users,
    category: "soft",
    rarity: "epic",
    mastery: 88,
    lore: "Party synergy buff. Raids clear faster when the whole guild's stats are raised, not just one hunter's.",
    tags: ["teamwork"],
  },
  {
    id: "active-listening",
    name: "Active Listening",
    icon: Ear,
    category: "soft",
    rarity: "epic",
    mastery: 86,
    lore: "Perception passive. Hears what the requirement meant, not only what it said.",
    tags: ["communication"],
  },
  {
    id: "adaptability",
    name: "Adaptability",
    icon: Shuffle,
    category: "soft",
    rarity: "epic",
    mastery: 89,
    lore: "Terrain resistance. New stack, new domain, new patch notes — the Player re-specs without losing tempo.",
    tags: ["flexibility"],
  },

  // ── PURSUITS ────────────────────────────────────────────────
  {
    id: "ctf",
    name: "CTF Challenges",
    icon: Flag,
    category: "pursuits",
    rarity: "rare",
    mastery: 78,
    lore: "Training dungeons. Capture-the-flag runs that keep the security instincts sharp.",
    tags: ["security", "hobby"],
  },
  {
    id: "open-source",
    name: "Open Source",
    icon: GitBranch,
    category: "pursuits",
    rarity: "epic",
    mastery: 84,
    lore: "Guild-hall contributions. Code given to the commons — the realm levels up together.",
    tags: ["community"],
  },
  {
    id: "video-gaming",
    name: "Video Gaming",
    icon: Landmark,
    category: "pursuits",
    rarity: "legendary",
    mastery: 95,
    lore: "Origin story. Where the Player learned that characters grow by grinding — the philosophy this whole System runs on.",
    tags: ["games", "inspiration"],
  },
  {
    id: "podcasts",
    name: "Podcasts",
    icon: Headphones,
    category: "pursuits",
    rarity: "rare",
    mastery: 80,
    lore: "Passive XP stream. Long-form signal absorbed on the move.",
    tags: ["learning"],
  },
  {
    id: "continuous-learning",
    name: "Continuous Learning",
    icon: Rocket,
    category: "pursuits",
    rarity: "legendary",
    mastery: 97,
    lore: "The real main stat. Every other number on this sheet is downstream of this one.",
    tags: ["growth"],
  },
];

export function findSkill(id: string): SkillDetail | undefined {
  return skills.find((skill) => skill.id === id);
}
